from dogCatClassifier.components.data_ingestion import DataIngestion 
from dogCatClassifier.components.prepare_base_model import PrepareBaseModel
from dogCatClassifier.components.prepare_callback import PrepareCallback
from dogCatClassifier.components.training import Training
from dogCatClassifier.components.evaluation import Evaluation